ECommerce/Controllers/CartController.cs
using ECommerceMVC.Data;
using ECommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using ECommerceMVC.Helpers;
using Microsoft.AspNetCore.Authorization;
using ECommerceMVC.Services;

namespace ECommerceMVC.Controllers
{
	public class CartController : Controller
	{
		private readonly PaypalClient _paypalClient;
		private readonly EcommerceContext db;
		private readonly IVnPayService _vnPayservice;

		public CartController(EcommerceContext context, PaypalClient paypalClient, IVnPayService vnPayservice)
		{
			_paypalClient = paypalClient;
			db = context;
			_vnPayservice = vnPayservice;
		}

		public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(MySetting.CART_KEY) ?? new List<CartItem>();

		public IActionResult Index()
		{
			return View(Cart);
		}

		public IActionResult AddToCart(int id, int quantity = 1)
		{
			var gioHang = Cart;
			var item = gioHang.SingleOrDefault(p => p.MaHh == id);
			if (item == null)
			{
				var hangHoa = db.HangHoas.SingleOrDefault(p => p.MaHh == id);
				if (hangHoa == null)
				{
					TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
					return Redirect("/404");
				}
				item = new CartItem
				{
					MaHh = hangHoa.MaHh,
					TenHH = hangHoa.TenHh,
					DonGia = hangHoa.DonGia ?? 0,
					Hinh = hangHoa.Hinh ?? string.Empty,
					SoLuong = quantity
				};
				gioHang.Add(item);
			}
			else
			{
				item.SoLuong += quantity;
			}

			HttpContext.Session.Set(MySetting.CART_KEY, gioHang);

			return RedirectToAction("Index");
		}
		public IActionResult PlusCart(int id)
		{
			var gioHang = Cart;
			var item = gioHang.SingleOrDefault(p => p.MaHh == id);
			item.SoLuong += 1;			
			HttpContext.Session.Set(MySetting.CART_KEY, gioHang);

			return RedirectToAction("Index");
		}
		public IActionResult MinusCart(int id)
		{
			var gioHang = Cart;
			var item = gioHang.SingleOrDefault(p => p.MaHh == id);
			item.SoLuong -= 1;
			HttpContext.Session.Set(MySetting.CART_KEY, gioHang);

			return RedirectToAction("Index");
		}
		public IActionResult RemoveCart(int id)
		{
			var gioHang = Cart;
			var item = gioHang.SingleOrDefault(p => p.MaHh == id);
			if (item != null)
			{
				gioHang.Remove(item);
				HttpContext.Session.Set(MySetting.CART_KEY, gioHang);
			}
			return RedirectToAction("Index");
		}
		
		[Authorize]
		[HttpGet]
		public IActionResult Checkout()
		{
			if (Cart.Count == 0)
			{
				return Redirect("/");
			}

			ViewBag.PaypalClientdId = _paypalClient.ClientId;
			return View(Cart);
		}

		[Authorize]
		[HttpPost]
		public IActionResult Checkout(CheckoutVM model, string payment = "COD")
		{
			if (ModelState.IsValid)
			{
				if (payment == "Thanh toán VNPay")
				{
					var vnPayModel = new VnPaymentRequestModel
					{
						Amount = Cart.Sum(p => p.ThanhTien),
						CreatedDate = DateTime.Now,
						Description = $"{model.HoTen} {model.DienThoai}",
						FullName = model.HoTen,
						OrderId = new Random().Next(1000, 100000)
					};
					return Redirect(_vnPayservice.CreatePaymentUrl(HttpContext, vnPayModel));
				}

				var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID).Value;
				var khachHang = new KhachHang();
				if (model.GiongKhachHang)
				{
					khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
				}

				var hoadon = new HoaDon
				{
					MaKh = customerId,
					HoTen = model.HoTen ?? khachHang.HoTen,
					DiaChi = model.DiaChi ?? khachHang.DiaChi,
					DienThoai = model.DienThoai ?? khachHang.DienThoai,
					NgayDat = DateTime.Now,
					CachThanhToan = "COD",
					CachVanChuyen = "GRAB",
					MaTrangThai = 0,
					GhiChu = model.GhiChu
				};

				db.Database.BeginTransaction();
				try
				{

					db.Add(hoadon);
					db.SaveChanges();

					var cthds = new List<ChiTietHd>();
					foreach (var item in Cart)
					{
						cthds.Add(new ChiTietHd
						{
							MaHd = hoadon.MaHd,
							SoLuong = item.SoLuong,
							DonGia = item.DonGia,
							MaHh = item.MaHh,
							GiamGia = 0
						});
					}
					db.AddRange(cthds);
					db.SaveChanges();
					db.Database.CommitTransaction();

					HttpContext.Session.Set<List<CartItem>>(MySetting.CART_KEY, new List<CartItem>());

					return View("Success");
				}
				catch
				{
					db.Database.RollbackTransaction();
				}
			}

			return View(Cart);
		}

		[Authorize]
		public IActionResult PaymentSuccess()
		{
			return View("Success");
		}

		#region Paypal payment
		[Authorize]
		[HttpPost("/Cart/create-paypal-order")]
		public async Task<IActionResult> CreatePaypalOrder(CancellationToken cancellationToken)
		{
			// Thông tin đơn hàng gửi qua Paypal
			var tongTien = Cart.Sum(p => p.ThanhTien).ToString();
			var donViTienTe = "USD";
			var maDonHangThamChieu = "DH" + DateTime.Now.Ticks.ToString();

			try
			{
				var response = await _paypalClient.CreateOrder(tongTien, donViTienTe, maDonHangThamChieu);

				return Ok(response);
			}
			catch (Exception ex)
			{
				var error = new { ex.GetBaseException().Message };
				return BadRequest(error);
			}
		}

		[Authorize]
		[HttpPost("/Cart/capture-paypal-order")]
		public async Task<IActionResult> CapturePaypalOrder(string orderID, CancellationToken cancellationToken)
		{
			try
			{
				var response = await _paypalClient.CaptureOrder(orderID);

				// Lưu database đơn hàng của mình

				return Ok(response);
			}
			catch (Exception ex)
			{
				var error = new { ex.GetBaseException().Message };
				return BadRequest(error);
			}
		}

		#endregion

		[Authorize]
		public IActionResult PaymentFail()
		{
			return View();
		}

		[Authorize]
		public IActionResult PaymentCallBack()
		{
			var response = _vnPayservice.PaymentExecute(Request.Query);

			if (response == null || response.VnPayResponseCode != "00")
			{
				TempData["Message"] = $"Lỗi thanh toán VN Pay: {response.VnPayResponseCode}";
				return RedirectToAction("PaymentFail");
			}


			// Lưu đơn hàng vô database

			TempData["Message"] = $"Thanh toán VNPay thành công";
			return RedirectToAction("PaymentSuccess");
		}

	}
}

ECommerce/Controllers/HangHoaController.cs
using ECommerceMVC.Data;
using ECommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;

namespace ECommerceMVC.Controllers
{
	public class HangHoaController : Controller
	{
		private readonly EcommerceContext db;

		public HangHoaController(EcommerceContext conetxt)
		{
			db = conetxt;
		}

		public IActionResult Index(int? loai, int? page)
		{
			var hangHoas = db.HangHoas.AsQueryable();

			if (loai.HasValue)
			{
				hangHoas = hangHoas.Where(p => p.MaLoai == loai.Value);
				ViewData["CurrentLoai"] = loai.Value;
			}

			const int pageSize = 6;

			var totalProducts = hangHoas.Count();
			var totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

			if (page == null) { page = 1; }
			int skipN = (page.Value - 1) * pageSize;

			var result = hangHoas.OrderByDescending(p => p.TenHh)
								 .Skip(skipN)
								 .Take(pageSize)
								 .Select(p => new HangHoaVM
								 {
									 MaHh = p.MaHh,
									 TenHH = p.TenHh,
									 DonGia = p.DonGia ?? 0,
									 Hinh = p.Hinh ?? "",
									 MoTaNgan = p.MoTaDonVi ?? "",
									 TenLoai = p.MaLoaiNavigation.TenLoai
								 }).ToList();

			ViewBag.TotalPages = totalPages;
			ViewBag.CurrentPage = page;

			return View(result);
		}

		public IActionResult Search(string? query)
		{
			var hangHoas = db.HangHoas.AsQueryable();

			if (query != null)
			{
				hangHoas = hangHoas.Where(p => p.TenHh.Contains(query));
			}

			var result = hangHoas.Select(p => new HangHoaVM
			{
				MaHh = p.MaHh,
				TenHH = p.TenHh,
				DonGia = p.DonGia ?? 0,
				Hinh = p.Hinh ?? "",
				MoTaNgan = p.MoTaDonVi ?? "",
				TenLoai = p.MaLoaiNavigation.TenLoai
			});
			return View(result);
		}

		const int pageSize = 6;
		public IActionResult PhanTrang(int? page)
		{
			if (page == null) { page = 1; }
			int skipN = (page.Value - 1) * pageSize;
			var dsHangHoa = db.HangHoas.OrderByDescending(p => p.TenHh).Skip(skipN).Take(pageSize).ToList();

			var totalProducts = db.HangHoas.Count();
			var totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

			ViewBag.TotalPages = totalPages;

			return View("Index", dsHangHoa.Select(hh => new HangHoaVM
			{
				MaHh = hh.MaHh,
				TenHH = hh.TenHh,
				Hinh = hh.Hinh ?? "",
				DonGia = hh.DonGia ?? 0
			}));

		}
		
		public IActionResult Detail(int id)
		{
			var data = db.HangHoas
				.Include(p => p.MaLoaiNavigation)
				.SingleOrDefault(p => p.MaHh == id);
			if (data == null)
			{
				TempData["Message"] = $"Không thấy sản phẩm có mã {id}";
				return Redirect("/404");
			}

			var result = new ChiTietHangHoaVM
			{
				MaHh = data.MaHh,
				TenHH = data.TenHh,
				DonGia = data.DonGia ?? 0,
				ChiTiet = data.MoTa ?? string.Empty,
				Hinh = data.Hinh ?? string.Empty,
				MoTaNgan = data.MoTaDonVi ?? string.Empty,
				TenLoai = data.MaLoaiNavigation.TenLoai,
				SoLuongTon = 10,//tính sau
				DiemDanhGia = 5,//check sau
			};
			return View(result);
		}
	}
}

ECommerce/Controllers/HangHoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerceMVC.Data;

namespace ECommerceMVC.Controllers
{
    public class HangHoasController : Controller
    {
        private readonly EcommerceContext _context;

        public HangHoasController(EcommerceContext context)
        {
            _context = context;
        }

        // GET: HangHoas
        public async Task<IActionResult> Index()
        {
            var EcommerceContext = _context.HangHoas.Include(h => h.MaLoaiNavigation).Include(h => h.MaNccNavigation);
            return View(await EcommerceContext.ToListAsync());
        }

        // GET: HangHoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.MaLoaiNavigation)
                .Include(h => h.MaNccNavigation)
                .FirstOrDefaultAsync(m => m.MaHh == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // GET: HangHoas/Create
        public IActionResult Create()
        {
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai");
            ViewData["MaNcc"] = new SelectList(_context.NhaCungCaps, "MaNcc", "MaNcc");
            return View();
        }

        // POST: HangHoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHh,TenHh,TenAlias,MaLoai,MoTaDonVi,DonGia,Hinh,NgaySx,GiamGia,SoLanXem,MoTa,MaNcc")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hangHoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai", hangHoa.MaLoai);
            ViewData["MaNcc"] = new SelectList(_context.NhaCungCaps, "MaNcc", "MaNcc", hangHoa.MaNcc);
            return View(hangHoa);
        }

        // GET: HangHoas/Edit/5
       
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas.FindAsync(id);
            if (hangHoa == null)
            {
                return NotFound();
            }
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai", hangHoa.MaLoai);
            ViewData["MaNcc"] = new SelectList(_context.NhaCungCaps, "MaNcc", "MaNcc", hangHoa.MaNcc);
            return View(hangHoa);
        }

        // POST: HangHoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHh,TenHh,TenAlias,MaLoai,MoTaDonVi,DonGia,Hinh,NgaySx,GiamGia,SoLanXem,MoTa,MaNcc")] HangHoa hangHoa)
        {
            if (id != hangHoa.MaHh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hangHoa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HangHoaExists(hangHoa.MaHh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.Loais, "MaLoai", "MaLoai", hangHoa.MaLoai);
            ViewData["MaNcc"] = new SelectList(_context.NhaCungCaps, "MaNcc", "MaNcc", hangHoa.MaNcc);
            return View(hangHoa);
        }

        // GET: HangHoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.MaLoaiNavigation)
                .Include(h => h.MaNccNavigation)
                .FirstOrDefaultAsync(m => m.MaHh == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // POST: HangHoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hangHoa = await _context.HangHoas.FindAsync(id);
            if (hangHoa != null)
            {
                _context.HangHoas.Remove(hangHoa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HangHoaExists(int id)
        {
            return _context.HangHoas.Any(e => e.MaHh == id);
        }
    }
}

ECommerce/ViewComponents/MenuLoaiViewComponent.cs
using ECommerceMVC.Data;
using ECommerceMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceMVC.ViewComponents
{
	public class MenuLoaiViewComponent : ViewComponent
	{
		private readonly EcommerceContext db;

		public MenuLoaiViewComponent(EcommerceContext context) => db = context;

		public IViewComponentResult Invoke()
		{
			var data = db.Loais.Select(lo => new MenuLoaiVM
			{
				MaLoai = lo.MaLoai,
				TenLoai = lo.TenLoai,
				SoLuong = lo.HangHoas.Count
			}).OrderBy(p => p.TenLoai);

			return View(data); // Default.cshtml
			//return View("Default", data);
		}
	}
}

ECommerce/Views/HangHoa/Detail.cshtml
@model ECommerceMVC.ViewModels.ChiTietHangHoaVM
@{
	ViewData["Title"] = "Detail";
}

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
	<h1 class="text-center text-white display-6">Shop Detail</h1>
	<ol class="breadcrumb justify-content-center mb-0">
		<li class="breadcrumb-item"><a href="#">Home</a></li>
		<li class="breadcrumb-item"><a href="#">Hàng hóa</a></li>
		<li class="breadcrumb-item active text-white">@Model.TenHH</li>
	</ol>
</div>
<!-- Single Page Header End -->
<!-- Single Product Start -->
<div class="container-fluid py-5 mt-5">
	<div class="container py-5">
		<div class="row g-4 mb-5">
			<div class="col-lg-8 col-xl-9">
				<div class="row g-4">
					<div class="col-lg-6">
						<div class="border rounded">
							<a asp-action="Detail" asp-route-id="@Model.MaHh">
								<img src="~/Hinh/Hinh/HangHoa/@Model.Hinh" class="img-fluid rounded" alt="@Model.TenHH">
							</a>
						</div>
					</div>
					<div class="col-lg-6">
						<h4 class="fw-bold mb-3">@Model.TenHH</h4>
						<p class="mb-3">Category: @Model.TenLoai</p>
						<h5 class="fw-bold mb-3">$ @Model.DonGia</h5>
						<div class="d-flex mb-4">
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star text-secondary"></i>
							<i class="fa fa-star"></i>
						</div>
						<p class="mb-4">@Model.MoTaNgan</p>
						<form asp-action="AddToCart" asp-controller="Cart" asp-route-id="@Model.MaHh">
							<div class="input-group quantity mb-5" style="width: 100px;">
								<div class="input-group-btn">
									<button class="btn btn-sm btn-minus rounded-circle bg-light border" type="button">
										<i class="fa fa-minus"></i>
									</button>
								</div>
								<input type="text" class="form-control form-control-sm text-center border-0" value="1" name="quantity">
								<div class="input-group-btn">
									<button class="btn btn-sm btn-plus rounded-circle bg-light border" type="button">
										<i class="fa fa-plus"></i>
									</button>
								</div>
							</div>
							<button class="btn border border-secondary rounded-pill px-4 py-2 mb-4 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Mua hàng</button>
						</form>
					</div>
					<div class="col-lg-12">
						<nav>
							<div class="nav nav-tabs mb-3">
								<button class="nav-link active border-white border-bottom-0" type="button" role="tab"
										id="nav-about-tab" data-bs-toggle="tab" data-bs-target="#nav-about"
										aria-controls="nav-about" aria-selected="true">
									Thông tin hàng hóa
								</button>
								<button class="nav-link border-white border-bottom-0" type="button" role="tab"
										id="nav-mission-tab" data-bs-toggle="tab" data-bs-target="#nav-mission"
										aria-controls="nav-mission" aria-selected="false">
									Đánh giá
								</button>
							</div>
						</nav>
						<div class="tab-content mb-5">
							<div class="tab-pane active" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
								@Model.ChiTiet
							</div>
							<div class="tab-pane" id="nav-mission" role="tabpanel" aria-labelledby="nav-mission-tab">
							
							</div>
							<div class="tab-pane" id="nav-vision" role="tabpanel">
								<p class="text-dark">
									Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam
									amet diam et eos labore. 3
								</p>
								<p class="mb-0">
									Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore.
									Clita erat ipsum et lorem et sit
								</p>
							</div>
						</div>
					</div>
					<form action="#">
						<h4 class="mb-5 fw-bold">Leave a Reply</h4>
						<div class="row g-4">
							<div class="col-lg-6">
								<div class="border-bottom rounded">
									<input type="text" class="form-control border-0 me-4" placeholder="Yur Name *">
								</div>
							</div>
							<div class="col-lg-6">
								<div class="border-bottom rounded">
									<input type="email" class="form-control border-0" placeholder="Your Email *">
								</div>
							</div>
							<div class="col-lg-12">
								<div class="border-bottom rounded my-4">
									<textarea name="" id="" class="form-control border-0" cols="30" rows="8" placeholder="Your Review *" spellcheck="false"></textarea>
								</div>
							</div>
							<div class="col-lg-12">
								<div class="d-flex justify-content-between py-3 mb-5">
									<div class="d-flex align-items-center">
										<p class="mb-0 me-3">Please rate:</p>
										<div class="d-flex align-items-center" style="font-size: 12px;">
											<i class="fa fa-star text-muted"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
										</div>
									</div>
									<a href="#" class="btn border border-secondary text-primary rounded-pill px-4 py-3"> Post Comment</a>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="col-lg-4 col-xl-3">
				<div class="row g-4 fruite">
					<div class="col-lg-12">
						@await Html.PartialAsync("_TimKiemPanel")
						@await Component.InvokeAsync("MenuLoai")
					</div>
				
					
				</div>
			</div>
		</div>
		
	</div>
</div>
<!-- Single Product End -->

ECommerce/Views/HangHoa/Index.cshtml
@model IEnumerable<ECommerceMVC.ViewModels.HangHoaVM>

@{
	ViewData["Title"] = "Index";
	Layout = "_DanhSachHangHoa";
}

<!-- Single Page Header start -->
@section BreadCum {
	<div class="container-fluid page-header py-5">
		<h1 class="text-center text-white display-6">Shop</h1>
		<ol class="breadcrumb justify-content-center mb-0">
			<li class="breadcrumb-item"><a href="#">Home</a></li>
			<li class="breadcrumb-item"><a href="#">Pages</a></li>
			<li class="breadcrumb-item active text-white">Shop</li>
		</ol>
	</div>
}
<!-- Single Page Header End -->

@await Html.PartialAsync("ProductItem", Model)

<div class="col-12">
	<div class="pagination d-flex justify-content-center mt-5">
		<a asp-action="Index" asp-route-page="1" asp-route-loai="@ViewData["CurrentLoai"]">&laquo;</a>
		@for (int i = 1; i <= ViewBag.TotalPages; i++)
		{
			<a asp-action="Index" asp-route-page="@i" asp-route-loai="@ViewData["CurrentLoai"]">@i</a>
		}
		<a asp-action="Index" asp-route-page="@ViewBag.TotalPages" asp-route-loai="@ViewData["CurrentLoai"]">&raquo;</a>
	</div>
</div>

ECommerce/Views/HangHoa/ProductItem.cshtml
@model IEnumerable<ECommerceMVC.ViewModels.HangHoaVM>

@foreach (var item in Model)
{
	<div class="col-md-6 col-lg-6 col-xl-4">
		<div class="rounded position-relative fruite-item">
			<div class="fruite-img">
				<a asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.MaHh">
					<img src="~/Hinh/Hinh/HangHoa/@item.Hinh" class="img-fluid w-100 rounded-top" alt="@item.TenHH">
				</a>
			</div>
			<div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">@item.TenLoai</div>
			<div class="p-4 border border-secondary border-top-0 rounded-bottom">
				<a asp-action="Detail" asp-controller="HangHoa" asp-route-id="@item.MaHh"><h4>@item.TenHH</h4></a>
				<p>@item.MoTaNgan</p>
				<div class="d-flex justify-content-between flex-lg-wrap">
					<p class="text-dark fs-5 fw-bold mb-0">$@item.DonGia</p>
					<a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.MaHh" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Đưa vào giỏ</a>
				</div>
			</div>
		</div>
	</div>
}

ECommerce/Views/HangHoa/Search.cshtml
@model IEnumerable<ECommerceMVC.ViewModels.HangHoaVM>
@{
    ViewData["Title"] = "Search";
    Layout = "_DanhSachHangHoa";
}

<h1>Search</h1>

@await Html.PartialAsync("ProductItem", Model)